name: Publish in the Wippy Registry

on:
  push:
    tags:
      - 'v*'

concurrency:
  group: publish

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Publishing
        uses: wippyai/action-module-release@main
        with:
          directory: .
          tag: ${{ github.ref_name }}
          username: ${{ secrets.WIPPY_USERNAME }}
          password: ${{ secrets.WIPPY_PASSWORD }}
